[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

lib_deps = https://github.com/nitacku/nI2C.git
           thomasfredericks/Bounce2

extra_scripts = pre:scripts/generate_protocol.py

monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
